* wucuo (v0.0.7)

[[http://melpa.org/#/wucuo][file:http://melpa.org/packages/wucuo-badge.svg]]
[[http://stable.melpa.org/#/wucuo][file:http://stable.melpa.org/packages/wucuo-badge.svg]]

Spell check code containing camel case words.

- Support both aspell and hunspell
- Works out of box. Aspell's "--run-together" is optional
- Users have freedom to customize where to spell check and which dictionary to use
* Install
wucuo is already uploaded to [[http://melpa.org]]. The best way to install is Emacs package manager.
* Setup
Please install either aspell or hunspell and corresponding dictionaries at first.

* Usage
Run =M-x wucuo-start=. It will setup and start =flyspell-mode=.

Or add below code into =~/.emacs= to enable =wucuo= for all programming languages,
#+begin_src elisp
(defun prog-mode-hook-setup ()
  (wucuo-start t))
(add-hook 'prog-mode-hook 'prog-mode-hook-setup)
#+end_src

Please note =flyspell-prog-mode= should not be enabled when using =wucuo=. It should be replaced by =wucuo=.

Some major modes configure and start flyspell by themselves. Their per mode flyspell configuration should be replaced by wucuo too.

See the "Tips" or just contact me for the solution.
* Tips
** Change dictionaries
See =wucuo-aspell-language-to-use= and =wucuo-hunspell-dictionary-base-name=
** Only check words using certain font faces
#+begin_src elisp
(setq wucuo-personal-font-faces-to-check '(font-lock-comment-face))
#+end_src
** Flyspell wrongly mark some word as typo
There are three solutions.
*** Emacs Lisp setup
#+begin_src javascript
(defun my-checker (word)
  "If WORD is typo, return t."
  t)
(setq wucuo-extra-predicate #'my-checker)
#+end_src
*** Create personal dictionary for aspell
Run =M-x wucuo-create-aspell-personal-dictionary=
*** Create personal dictionary for hunspell
Run =M-x wucuo-create-hunspell-personal-dictionary=
** Speed up checking if aspell is used
#+begin_src elisp
(setq ispell-extra-args "--run-together")
#+end_src
** If the major mode has its own flyspell configuration
I've not found any better solution than my program.

So I strongly recommend using wucuo to replace default flyspell configuration of any major mode,
#+begin_src elisp
(wucuo-setup-major-mode "typescript-mode")
#+end_src

Or if you need replace the default configuration of multiple major modes, you can use below code, 
#+begin_src elisp
(setq wucuo-major-modes-to-setup-by-force
      '("typescript-mode" "emacs-lisp-mode"))
(wucuo-start t)
#+end_src
* Contact me
Report bug at [[https://github.com/redguardtoo/wucuo]].
